//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_USER_MST_STREET
    {
        public int ADUM_USER_CODE { get; set; }
        public Nullable<byte> SERVER_ID { get; set; }
        public int APP_ID { get; set; }
        public string ADUM_USER_ID { get; set; }
        public string ADUM_USER_NAME { get; set; }
        public string ADUM_LOGIN_ID { get; set; }
        public string ADUM_PASSWORD { get; set; }
        public string ADUM_EMPLOYEE_ID { get; set; }
        public string ADUM_DESIGNATION { get; set; }
        public string ADUM_MOBILE { get; set; }
        public string ADUM_EMAIL { get; set; }
        public string LOCAL_USER_NAME { get; set; }
        public string PROFILE_IMAGE { get; set; }
        public Nullable<System.DateTime> ADUM_FRDT { get; set; }
        public Nullable<System.DateTime> ADUM_TODT { get; set; }
        public Nullable<bool> ADUM_STATUS { get; set; }
        public Nullable<bool> UPDATE_FLAG { get; set; }
        public Nullable<System.DateTime> LAST_UPDATE { get; set; }
        public Nullable<int> AD_USER_TYPE_ID { get; set; }
        public string MOBILE_ID { get; set; }
        public Nullable<bool> IS_ACTIVE { get; set; }
        public string IMO_NO { get; set; }
    }
}
