//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class country_states
    {
        public int id { get; set; }
        public string country_name { get; set; }
        public string state_name { get; set; }
        public string state_name_mar { get; set; }
        public string state_3_code { get; set; }
        public string state_2_code { get; set; }
    }
}
