//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    
    public partial class CurrentAllUserLocation_Result3
    {
        public Nullable<int> userid { get; set; }
        public string userName { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string lat { get; set; }
        public string @long { get; set; }
        public string address { get; set; }
        public string area { get; set; }
        public string userMobileNumber { get; set; }
    }
}
