//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamePlayerDetail
    {
        public int ID { get; set; }
        public string PlayerId { get; set; }
        public Nullable<int> GameId { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> Score { get; set; }
        public string DeviceId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
