//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameDetail
    {
        public int GameDetailsID { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> RightAnswerID { get; set; }
        public Nullable<int> Point { get; set; }
        public Nullable<int> GameMasterID { get; set; }
        public Nullable<int> SloganID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    }
}
