//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game_AnswerType
    {
        public int AnswerTypeId { get; set; }
        public string AnswerType { get; set; }
        public string AnswerTypeMar { get; set; }
        public Nullable<int> GameMasterID { get; set; }
        public string AnswerTypeHindi { get; set; }
    }
}
