//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class GramCleaningComplient
    {
        public int CleaningComplientId { get; set; }
        public string Place { get; set; }
        public string Ward_No_ { get; set; }
        public string Details { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Number { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Tip { get; set; }
        public string Image { get; set; }
        public string Lat_Log { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> languageId { get; set; }
        public string status { get; set; }
        public string userId { get; set; }
        public string status_description { get; set; }
        public string status_image_url { get; set; }
        public string ref_id { get; set; }
        public Nullable<int> Type { get; set; }
    }
}
