//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class HouseList
    {
        public int Id { get; set; }
        public string ReferanceId { get; set; }
        public bool IsCheked { get; set; }
        public Nullable<int> HouseId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> AreaId { get; set; }
    }
}
