//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    
    public partial class houseCollection_Result1
    {
        public int gcId { get; set; }
        public Nullable<System.DateTime> gcDate { get; set; }
        public string userName { get; set; }
        public string houseOwner { get; set; }
        public string houseAddress { get; set; }
        public string gpBeforImage { get; set; }
        public string asgpAfterImage { get; set; }
        public string note { get; set; }
        public Nullable<int> garbageType { get; set; }
        public string vehicleNumber { get; set; }
    }
}
