//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sauchalay_feedback
    {
        public int SauchalayFeedback_ID { get; set; }
        public string ULB { get; set; }
        public string SauchalayID { get; set; }
        public Nullable<int> AppId { get; set; }
        public string Fullname { get; set; }
        public string MobileNo { get; set; }
        public string que1 { get; set; }
        public string que2 { get; set; }
        public string que3 { get; set; }
        public string Rating { get; set; }
        public string Feedback { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
