//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_1_4_QUESTION
    {
        public int Q_ID { get; set; }
        public string QUESTIOND { get; set; }
        public string Q_NO { get; set; }
        public string NOTE { get; set; }
    }
}
