//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_1_4_ANSWER
    {
        public int ANS_ID { get; set; }
        public int Q_ID { get; set; }
        public string TOTAL_COUNT { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
        public Nullable<int> INSERT_ID { get; set; }
    
        public virtual SS_1_4_ANSWER SS_1_4_ANSWER1 { get; set; }
        public virtual SS_1_4_ANSWER SS_1_4_ANSWER2 { get; set; }
    }
}
