//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS_1_7_ANSWER
    {
        public int Trno { get; set; }
        public int id { get; set; }
        public Nullable<int> No_water_bodies { get; set; }
        public Nullable<int> No_drain_nallas { get; set; }
        public Nullable<int> No_locations { get; set; }
        public Nullable<int> No_outlets { get; set; }
        public Nullable<int> INSERT_ID { get; set; }
        public Nullable<System.DateTime> INSERT_DATE { get; set; }
    }
}
