//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class StreetSweepingBeat
    {
        public int BeatId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ReferanceId1 { get; set; }
        public string ReferanceId2 { get; set; }
        public string ReferanceId3 { get; set; }
        public string ReferanceId4 { get; set; }
        public string ReferanceId5 { get; set; }
    }
}
