//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class tehsil
    {
        public int id { get; set; }
        public string name { get; set; }
        public string name_mar { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> district { get; set; }
        public Nullable<bool> IsCheked { get; set; }
    }
}
