//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeritoryMaster
    {
        public int Id { get; set; }
        public string Area { get; set; }
        public string AreaMar { get; set; }
        public Nullable<int> wardId { get; set; }
    }
}
