//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehical_QR_Master
    {
        public int vqrId { get; set; }
        public string VehicalNumber { get; set; }
        public string VehicalQRCode { get; set; }
        public string ReferanceId { get; set; }
        public Nullable<System.DateTime> modified { get; set; }
        public string FCMID { get; set; }
        public Nullable<System.DateTime> lastModifiedEntry { get; set; }
        public string RFIDTagId { get; set; }
        public string VehicalType { get; set; }
        public string Property_Type { get; set; }
    }
}
