//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleRegistration
    {
        public int vehicleId { get; set; }
        public Nullable<int> vehicleType { get; set; }
        public string vehicleNo { get; set; }
        public Nullable<int> areaId { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
