//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleType
    {
        public int vtId { get; set; }
        public string description { get; set; }
        public string descriptionMar { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
