//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_HSGetStreetDetails
    {
        public Nullable<int> userId { get; set; }
        public int SSId { get; set; }
        public string SSLat { get; set; }
        public string SSLong { get; set; }
        public string ReferanceId { get; set; }
        public Nullable<bool> QRStatus { get; set; }
        public Nullable<System.DateTime> QRStatusDate { get; set; }
        public Nullable<System.DateTime> lastModifiedDate { get; set; }
        public string qrEmpName { get; set; }
        public string SSName { get; set; }
        public string BinaryQrCodeImage { get; set; }
        public Nullable<int> FilterTotalCount { get; set; }
    }
}
