//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwachBharat.CMS.Dal.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class WM_Garbage_Details
    {
        public int GarbageDetailsID { get; set; }
        public Nullable<int> SubCategoryID { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Source { get; set; }
        public Nullable<System.DateTime> gdDate { get; set; }
    }
}
